CN Update for 41.42
TheIndieStone/ProjectZomboidTranslations pull request #349
Opened 2020-09-05 14:37 UTC by zlq4863947

2020-09-05 15:06 UTC, Mishasama requested changes
请勿脱离原意进行**“原创”**翻译

2020-09-05 15:06 UTC, Mishasama commented on CN/ItemName_CN.txt
> +    ItemName_Base.ClosedUmbrellaWhite = "白色雨伞（收起）",
原文根本没有颜色之分

2020-09-05 15:06 UTC, Mishasama commented on CN/ItemName_CN.txt
> +    ItemName_Radio.TvWideScreen = "宽屏电视机",
完全跟原意不一致

2020-09-05 15:06 UTC, Mishasama commented on CN/ItemName_CN.txt
> +    ItemName_Radio.WalkieTalkie5 = "军用对讲机",
与原文不符

2020-09-05 15:46 UTC, Alexa-Hong commented on CN/ItemName_CN.txt
> +    ItemName_Base.ClosedUmbrellaWhite = "白色雨伞（收起）",
ClosedUmbrella**White**
ClosedUmbrella**Red**
ClosedUmbrella**Blue**
ClosedUmbrella**Black**

2020-09-05 15:47 UTC, Alexa-Hong commented on CN/ItemName_CN.txt
> +    ItemName_Radio.TvWideScreen = "宽屏电视机",
Tv**Antique**
Tv**WideScreen**

2020-09-05 15:50 UTC, HansKaffee commented on CN/ItemName_CN.txt
> +    ItemName_Base.ClosedUmbrellaWhite = "白色雨伞（收起）",
原文是没有颜色之分，但是这样做并不会影响玩家对物品的理解，还能方便玩家分辨颜色。

2020-09-05 15:51 UTC, HansKaffee commented on CN/ItemName_CN.txt
> +    ItemName_Radio.TvWideScreen = "宽屏电视机",
ValuTech翻译成廉价技术就和原文一致了？

2020-09-05 15:55 UTC, zlq4863947 commented on CN/ItemName_CN.txt
> +    ItemName_Radio.WalkieTalkie5 = "军用对讲机",
游戏中有类似军用词汇，所以使用军用更符合游戏设定。
![image](https://user-images.githubusercontent.com/6490251/92308816-76e7cb00-efdb-11ea-95bb-b96285a86890.png)

2020-09-05 15:59 UTC, zlq4863947 commented on CN/ItemName_CN.txt
> +    ItemName_Base.ClosedUmbrellaWhite = "白色雨伞（收起）",
我们不喜欢你的独裁翻译，这个翻译是我们汉化组内共同探讨的结果。
要么加群，一起翻译，要么别捣乱

2020-09-05 16:51 UTC, zhaotaq commented on CN/ItemName_CN.txt
> +    ItemName_Base.ClosedUmbrellaWhite = "白色雨伞（收起）",
已测试，新翻译可以解决，“玩家找不到想要的伞”的问题。
![image](https://user-images.githubusercontent.com/28332586/92309746-d2fe1f80-efda-11ea-95e5-9c3d1409f7a3.png)
![image](https://user-images.githubusercontent.com/28332586/92309765-e9a47680-efda-11ea-9dfb-39aa81f8f8b1.png)

2020-09-07 07:37 UTC, nsKpz commented
Can someone summarize the discussions for me?

2020-09-07 08:09 UTC, zlq4863947 commented
@nsKpz 
The content submitted now is the result of a joint discussion among 5 people in our Chinese translation team. Please merge.
After the merger, we will announce to Chinese players on these two websites: 
- [blibli](https://www.bilibili.com/)
- [tieba](https://tieba.baidu.com/f?kw=%E5%83%B5%E5%B0%B8%E6%AF%81%E7%81%AD%E5%B7%A5%E7%A8%8B)

Similar to the public address after the last merger:
https://www.bilibili.com/read/cv7516134
https://tieba.baidu.com/p/6931027044?pid=134687771289&red_tag=3013153447#134687771289

If most players return some words that are not accurate enough, the revised content will be submitted in the next PR

2020-09-07 10:20 UTC, nsKpz commented
I'm more interested in the discussions that already happened and would like to know the context of them before merging.

2020-09-07 11:06 UTC, Alexa-Hong commented
> I'm more interested in the discussions that already happened and would like to know the context of them before merging.

1. 
ItemName_Base.ClosedUmbrellaBlack = "黑色雨伞（收起）",
    ItemName_Base.ClosedUmbrellaBlue = "蓝色雨伞（收起）",
    ItemName_Base.ClosedUmbrellaRed = "红色雨伞（收起）",
    ItemName_Base.ClosedUmbrellaWhite = "白色雨伞（收起）",
“黑色”“蓝色”“红色”“白色”are all colors
@zlq4863947 adds these prefixes so that players can identify the color of the umbrella
Misha believes since the english translation of them do not include the idea of color so Chinese translation should ignore the color part too.

2.
 ItemName_Radio.TvAntique = "复古电视机",
 ItemName_Radio.TvBlack = "显像管电视机",
 ItemName_Radio.TvWideScreen = "宽屏电视机",

 ItemName_Radio.TvAntique = "复古电视机", should be fine

but they have different ideas about ItemName_Radio.TvBlack = "显像管电视机", and  ItemName_Radio.TvWideScreen = "宽屏电视机",
zlq4863947 changes "ValuTech Television"(English translation) from  "电视机（廉价技术）"(Misha's CN translation) to  "显像管电视机"(Zlq's CN translation), "电视机（廉价技术）" means “TV（cheap technology）” in English while  "显像管电视机" means "cathode-ray tube TV" in English.

3. ItemName_Radio.WalkieTalkie5 = "美军对讲机",
    ItemName_Radio.WalkieTalkie5 = "军用对讲机",
“对讲机” means WalkieTalkie
Misha prefer "美军”， which measn "US army”, she suggests translation should loyal to the original text
and zlq prefer "军用" , which means "military”， he changed it because there are other words that use "军用" as well, like “军用头盔”（Military Helmet），"军用沙漠迷彩夹克"(Military Desert Camo Jacket)

2020-09-07 11:09 UTC, Alexa-Hong commented
and to be honest, they do not come to an agreement.
This may go on and on and on if they can't find a way working together.

2020-09-07 11:39 UTC, nsKpz commented
Thank you @Alexa-Hong 

1.
Regarding Umbrellas and their colours, we have other languages that explicitly state the colour, too. This makes sense to me, and we've considered adding the name to the English original, too. Even if not, I don't see how it would be a valid reason not to change it to something that benefits players more than the original translation. If anything, it'd be a reason for us to adjust the original name as well. This is what this Github is all about.

I have a question regarding these, though. When a player sorts their inventory, players usually prefer items of a different colour to still appear together in the list. 
I noticed that the Chinese name for the umbrellas has the status (collapsed, opened) in brackets for that reason, too. Would it be better to have in the format of "Umbrella - Red (closed)" then? 

I.e. a colour prefix would cause umbrellas of different colours to not appear together when the inventory is sorted by name.

So as an example, would the following work in Chinese?

Umbrella - Black (Collapsed)
雨伞 - 黑色（折叠）

______________________

2. 
If our fake-brand (ValuTech) doesn't have a place in a translation, I am alright with simply calling the item what it is. We do have other items as well as story elements that will mention the name, though, so if there can be a way to have the name still in there while also calling the item something better, that would be preferable. 

The name CRT TV might be a bit odd, as our game takes place at a time where there were no other kinds of TV devices, so nobody would have referred to them as such in the game world, if you know what I mean? 
A more general name for TV might be better?
______________________

3.
I have no real preference either way, so I'm letting you guys come to a consensus if Chinese players would prefer "US Army" or "Military".

2020-09-08 08:10 UTC, zlq4863947 commented
@Alexa-Hong @nsKpz 
Thank you very much for your suggestions. 
Our translation team has just been established. 
It takes some time to coordinate and discuss, please give us some time and submit the updated content later

2020-09-13 16:01 UTC, zlq4863947 commented
@nsKpz 

Here are the results of our discussion:
1. We totally agree with you, This way players can classify umbrellas better , and the umbrella-black (foldable) has been tested in the game without problems.
<img width="327" alt="1" src="https://user-images.githubusercontent.com/6490251/93022727-acb53100-f625-11ea-86df-2906694db5b1.png">
<img width="279" alt="2" src="https://user-images.githubusercontent.com/6490251/93022730-af178b00-f625-11ea-84b9-d4d48152bc16.png">

2. We have changed the brand name of the TV.
3. We have consulted many Chinese players, and they all think the word "military" is better .

If there are no other questions, please merge our translated text

2020-09-14 13:04 UTC, merged