Update for CN
TheIndieStone/ProjectZomboidTranslations pull request #354
Opened 2020-09-14 15:54 UTC by zlq4863947

2020-09-15 10:33 UTC, nsKpz requested changes

2020-09-19 08:46 UTC, moonlight-pz commented on CN/ItemName_CN.txt
> +    ItemName_Base.Apron_PileOCrepe = "可丽家 服务员围裙",
Localized translation，for example：（english：Oreo）（chinese：奥利奥）this game's pet（english：Spiffo）(chinese:斯皮福)

2020-09-20 15:30 UTC, zlq4863947 commented on CN/ItemName_CN.txt
> +    ItemName_Base.WhiskeyFull = "威士忌",
modified to 波本威士忌

2020-09-20 15:32 UTC, zlq4863947 commented on CN/ItemName_CN.txt
> +    ItemName_Base.TVDinner = "冷冻便当",
After our discussion, it has been changed to: `快捷盒饭`。
By the way, there is no non-expiring bento in the real world

2020-09-20 19:29 UTC, merged

2020-12-20 06:54 UTC, moonlight-pz commented
> @zlq4863947 @moonlight-pz @Mishasama
> 
> Hey guys.
> Any further updates to the chinese translation? Last update has been a while :)

I have submitted：https://github.com/project-zomboid-cn-translation/ProjectZomboidTranslations/pull/26
Will be submitted to you after review within the group

2020-12-25 18:15 UTC, Mishasama commented
> @zlq4863947 @moonlight-pz @Mishasama
> 
> Hey guys.
> Any further updates to the chinese translation? Last update has been a while :)

Sorry, I will not push any more updates for CHS since they take control dominance. I can't guarantee the quality of the translation under that.